#Spring Configuration
spring:
   application:
      name: mysite
   #devtools - live reload
   devtools:
      livereload:
         enabled: true
   #mvc
   mvc:
      static-path-pattern: /assets/**
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
      resources:
         static-location: classpath:/assets/, file:/mysite-uploads/

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB

   # messages resources(internalization, i18n)
   messages:
      always-message-format: true
      basename: web/messages_ko
      encoding: utf-8


   aop:
      auto: true
      proxy-target-class: true
      

# server
server:
   port: 9090